league/urls.py
from django.urls import path
from . import views

app_name = 'league'
urlpatterns = [
    path('', views.index, name='index'),
    path('p/<int:player_id>', views.player, name='player'),
    path('l/<int:league_id>', views.league, name='league'),
    path('g/<int:game_id>', views.game, name='game'),
    path('c/<int:league_id>', views.chart, name='chart'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
     # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
     # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pugberus/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

admin.site.site_header = 'Pugberus Admin'
admin.site.site_title = 'Pugberus Site Admin'

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', include('polls.urls')),
    path('league/', include('league.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

league/models.py
from django.db import models

class Player(models.Model):
    """A game player"""
    handle = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.handle

class League(models.Model):
    """A league"""
    name = models.CharField(max_length=200)
    players = models.ManyToManyField(Player)
    def __str__(self) -> str:
        return self.name
    
class Game(models.Model):
    """An individual game or match"""
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    game_no = models.IntegerField()
    game_date = models.DateField()
    result = models.CharField(max_length=200, blank=True)
    def __str__(self) -> str:
        return f"{self.league.name} #{self.game_no} {self.game_date:%m/%d}" # Date format
    def winner(self):
        """Return game winner (lowest score)"""
        scores = self.score_set.all()
        if len(scores) == 0:
            return None
        else:
            return min(scores, key=lambda x: x.score)

class Score(models.Model):
    """One player's performance within a match"""
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    defeat = models.BooleanField()
    score = models.IntegerField()
    guesses = models.CharField(max_length=200, blank=True)
    raw_score = models.CharField(max_length=200, blank=True)
    def __str__(self) -> str:
        return f'{self.player} {self.game} Score: {self.score}'

polls/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def votes_total(self):
        return sum(choice.votes for choice in self.choice_set.all())

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    def votes_percent(self):
        return 100 * self.votes / self.question.votes_total()

league/views.py
from django.db.models import Avg, Min, Max, Count, Func, FloatField
from django.shortcuts import get_object_or_404, render
from league.models import Game, League, Player

def index(request):
    leagues = League.objects.all()
    context = {
        'leagues': leagues,
    }
    return render(request, 'league/index.html', context)

def league(request, league_id):
    _league = get_object_or_404(League, pk=league_id)
    _players = _league.game_set.values('score__player__handle', 'score__player__id').annotate(
        avg_score=Func(Avg('score__score'), 1, function='ROUND', output_field=FloatField()),
        min_score=Min('score__score'),
        max_score=Max('score__score'),
        count=Count('id')
    )
    _games = _league.game_set.order_by('-game_no').all()
    return render(request, 'league/league.html', {'league': _league, 'games': _games, 'players': _players})

def player(request, player_id):
    _player = get_object_or_404(Player, pk=player_id)
    _scores = _player.score_set.order_by('game__league__name', '-game__game_no')
    _leagues = _player.score_set.values('game__league__name', 'game__league__id').annotate(
        avg_score=Func(Avg('score'), 1, function='ROUND', output_field=FloatField()),
        min_score=Min('score'),
        max_score=Max('score'),
        count=Count('id')
    )
    return render(request, 'league/player.html', {'player': _player, 'scores': _scores, 'leagues': _leagues})

def game(request, game_id):
    _game = get_object_or_404(Game, pk=game_id)
    return render(request, 'league/game.html', {'game': _game})

def chart(request, league_id):
    _league = get_object_or_404(League, pk=league_id)
    _players = _league.game_set.values('score__player__handle', 'score__player__id').annotate(
        avg_score=Func(Avg('score__score'), 1, function='ROUND', output_field=FloatField()),
        min_score=Min('score__score'),
        max_score=Max('score__score'),
        count=Count('id')
    )
    _games = _league.game_set.order_by('-game_no').all()
    return render(request, 'league/chart.html', {'league': _league, 'games': _games, 'players': _players})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

pugberus/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

league/templates/league/chart.html
{% extends "base.html" %}

{% block title %}
Pugberus | {{ league.name }}
{% endblock %}

{% block topsubbar %}
<a href="{% url 'league:index' %}">Leagues</a> > {{ league.name }}
{% endblock %}

{% block content %}
<table class="center mb-8 mw-80">
    <caption>Summary</caption>
    <tr>
        <th>Player</th>
        <th>#</th>
        <th>Min</th>
        <th>Avg</th>
        <th>Max</th>
    </tr>
    {% for player in players %}
    <tr>
        <td><a href="{% url 'league:player' player.score__player__id %}">{{ player.score__player__handle }}</a></td>
        <td>{{ player.count }}</td>
        <td>{{ player.min_score }}</td>
        <td>{{ player.avg_score }}</td>
        <td>{{ player.max_score }}</td>
    </tr>
    {% endfor %}
</table>
<table class="center mb-8 mw-80">
    <caption>Games | <a href="{% url 'league:league' league.id %}">Table</a> • Chart</caption>
    <tr>
        <td>
            <div id="myplot"></div>
        </td>
    </tr>
</table>
<style>
    .plot {
        background: none;
    }
</style>
<script type="module">
    import * as Plot from "https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6/+esm";
    const data = [
    {% for game in games %}
    {% for score in game.score_set.all %}
    { Date: new Date("{{ game.game_date }}"), Player: "{{ score.player.handle }}", Score: {{ score.score }} },
    {% endfor %}
    {% endfor %}
    ]
    const plot = Plot.plot({
        className: 'plot',
        color: { legend: true },
        marks: [
            Plot.lineY(data, { x: "Date", y: "Score", stroke: "Player" }),
        ]
    });
    setTimeout(() => {
        const div = document.querySelector("#myplot");
        div.append(plot);
    }, 100);
</script>
{% endblock %}

league/templates/league/game.html
{% extends "base.html" %}

{% block title %}
Pugberus | {{game.league.name}} #{{ game.game_no }}
{% endblock %}

{% block content %}
<table class="center mb-8 mw-80">
    <caption><a href="{% url 'league:league' game.league.id %}">{{game.league.name}}</a>
    #{{ game.game_no }} - {{ game.game_date }}</caption>
    <tr>
        <th width="80%"></th>
        <th width="10%">Defeat</th>
        <th width="10%">Score</th>
    </tr>
    {% for score in game.score_set.all %}
    <tr>
        <td>
            <a href="{% url 'league:player' score.player.id %}">
                {{ score.player.handle }}
            </a>
        </td>
        <td>
        {% if score.defeat %}
        Y
        {% else %}
        -
        {% endif %}
        </td>
        <td>{{ score.score }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

league/templates/league/index.html
{% extends "base.html" %}

{% block title %}
Pugberus | Leagues
{% endblock %}

{% block content %}
<h1>Leagues</h1>
{% if leagues %}
<ul>
    {% for league in leagues %}
    <li><a href="{% url 'league:league' league.id %}">{{ league.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No leagues are available.</p>
{% endif %}
{% endblock %}

league/templates/league/league.html
{% extends "base.html" %}

{% block title %}
Pugberus | {{ league.name }}
{% endblock %}

{% block content %}
<table class="center mb-8 mw-80">
    <caption>{{ league.name }} - Summary</caption>
    <tr>
        <th width="60%">Player</th>
        <th width="10%">#</th>
        <th width="10%">Min</th>
        <th width="10%">Avg</th>
        <th width="10%">Max</th>
    </tr>
    {% for player in players %}
    <tr>
        <td><a href="{% url 'league:player' player.score__player__id %}">{{ player.score__player__handle }}</a></td>
        <td>{{ player.count }}</td>
        <td>{{ player.min_score }}</td>
        <td>{{ player.avg_score }}</td>
        <td>{{ player.max_score }}</td>
    </tr>
    {% endfor %}
</table>
<table class="center mb-8 mw-80">
    <caption>Games | Table • <a href="{% url 'league:chart' league.id %}">Chart</a></caption>
    <tr>
        <th width="60%"></th>
        <th width="30%">Winner</th>
        <th width="10%">Score</th>
    </tr>
    {% for game in games %}
    <tr>
        <td>{{game.game_date}} - #<a href="{% url 'league:game' game.id %}">{{game.game_no}}</a></td>
        <td>{{game.winner.player.handle}}</td>
        <td>{{game.winner.score}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

league/templates/league/player.html
{% extends "base.html" %}

{% block title %}
Pugberus | {{ player.handle }}
{% endblock %}

{% block content %}
<table class="center mb-8 mw-80">
    <caption>{{ player.handle }} - Summary</caption>
    <tr>
        <th width="60%">League</th>
        <th width="10%">#</th>
        <th width="10%">Min</th>
        <th width="10%">Avg</th>
        <th width="10%">Max</th>
    </tr>
    {% for league in leagues %}
    <tr>
        <td><a href="{% url 'league:league' league.game__league__id %}">{{ league.game__league__name }}</a></td>
        <td>{{ league.count }}</td>
        <td>{{ league.min_score }}</td>
        <td>{{ league.avg_score }}</td>
        <td>{{ league.max_score }}</td>
    </tr>
    {% endfor %}
</table>
<table class="center mb-8 mw-80">
    <caption>Games</caption>
    <tr>
        <th width="60%"></th>
        <th width="30%">Date</th>
        <th width="10%">Score</th>
    </tr>
    {% for score in scores %}
    <tr>
        <td>{{score.game.league.name}} #<a href="{% url 'league:game' score.game.id %}">{{ score.game.game_no }}</a></td>
        <td>{{score.game.game_date}}</td>
        <td>{{ score.score }}</td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'league:index' %}">Back to main</a>
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block title %} 
Pugberus | {{question.question_text}} 
{% endblock %}

{% block content %}
<style>
    .poll-option {
        background-color: clear;
        border-color: var(--link-color);
        border-radius: 4px;
        border-style: solid;
        border-width: 1px;
        box-sizing: border-box;
        color: var(--link-color);
        cursor: pointer;
        display: block;
        height: 41px;
        line-height: 21px;
        min-height: 41px;
        padding-bottom: 9px;
        padding-left: 12px;
        padding-right: 24px;
        padding-top: 9px;
        position: relative;
        margin-bottom: 8px;
        max-width: 550px;
    }

    .poll-option:hover {
        background-color: var(--link-color);
        color: black;
    }

    .poll-option-text {
        font-family: sans-serif;
        font-kerning: auto;
        font-size: 14px;
        font-weight: 600;
        height: 21px;
        line-height: 21px;
        overflow-wrap: break-word;
        text-align: center;
        word-break: break-word;
    }
</style>
<script>
    function setAndSubmit(value) {
        document.getElementById("choice").value = value;
        document.getElementById("form").submit();
    }
</script>
<form id="form" action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="hidden" name="choice" id="choice">
    {% for choice in question.choice_set.all %}
    <div class="poll-option" onclick="setAndSubmit('{{ choice.id }}')">
        <div class="poll-option-text">{{ choice.choice_text }}</div>
    </div>
    {% endfor %}
    <noscript>
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </noscript>
    <p>
        {{question.votes_total}} votes
        •
        <a href={% url 'polls:results' question.id %}>Show Results</a>
    </p>
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block title %}
Pugberus | Polls
{% endblock %}

{% block content %}
<h1>Polls</h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block title %}
Pugberus | Poll Results
{% endblock %}

{% block content %}
<style>
  .bar-cell {
    border: 1px var(--link-color) solid;
    width: 240px;
  }

  .bar-text {
    display: block;
    margin: 2px;
    width: 20px;
    height: 20px;
    background-color: var(--link-color);
  }
</style>
<h1>{{ question.question_text }}</h1>
<table style="padding: 0 0 8px 0">
  {% for choice in question.choice_set.all %}
  <tr>
    <td style="padding-right: 20px">{{ choice.choice_text }}</td>
    <td class="bar-cell">
      <div class="bar-text" style="width: {{ choice.votes_percent }}%;"></div>
    </td>
    <td>{{ choice.votes }}</td>
    <td>{{ choice.votes_percent|floatformat:1 }}%</td>
  </tr>
  {% endfor %}
</table>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

pugberus/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'pugberus.png' %}">
</head>
<body>
    <div class="topbar">
        <div class="container">
            <div class="logo">
                <a href="{% url 'home' %}">Pugberus</a>
                
            </div>
            <ul class="nav">
                <li><a href="{% url 'polls:index' %}">Polls</a></li>
                <li><a href="{% url 'league:index' %}">League</a></li>
                <li>
                    <a href="{% url 'admin:index' %}">
                    {% if request.user.is_authenticated  %}
                        Admin
                    {% else %}
                        Login
                    {% endif %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

pugberus/templates/home.html
{% extends "base.html" %}

{% block title %}
Pugberus | Home
{% endblock %}

{% block content %}
{% endblock %}